Repository prgrms-aibe-devcourse/AIBE2_FinalProject_NoModel_FE, pull requests merged in 2025-09, with the labels that each got.

#11 feat: 어드민 기능 및 인증 시스템 개선
  .coderabbit.yml
  src/App.tsx
  src/components/AIModelBrowser.tsx
  src/components/ImageViewer.tsx
  src/components/LandingPage.tsx
  src/components/ModelCreation.tsx
  src/components/ModelDetailDialog.tsx
  src/components/ModelMarketplace.tsx
  src/components/ModelMarketplace.tsx.backup
  src/components/ModelReportModal.tsx
  src/components/ModelSearch.tsx
  src/components/ModelSelectionPage.tsx
  src/components/MyModels.tsx
  src/components/MyPage.tsx
  src/components/ProfileSettings.tsx
  src/components/common/Navbar.tsx
  src/components/ui/input.tsx
  src/services/auth.ts
  src/services/modelApi.ts
  src/types/model.ts
Labels: ⚙️ Setting, ✨ Feature, 🔨 Refactor

#23 Feat 22: 포인트 API 연동 및 포트원 SDK 기반 카카오페이 결제 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/PointsSubscriptionPage.tsx
Labels: ✨ Feature

#28 Feat 26: 포인트&구독 페이지 CSS 디자인
  src/components/PointsSubscriptionPage.tsx
Labels: 🎨 Desgin

#31 Feat 9: 리뷰 등록, 마이페이지에서 수정, 삭제 ,조회 기능 프론트 연동
  src/App.tsx
  src/components/ImageGenerationWorkflow.tsx
  src/components/MyPage.tsx
  src/components/MyReviews.tsx
  src/components/ProjectRatingForm.tsx
  src/components/StarRating.tsx
  src/components/ui/dialog.tsx
  src/components/workflow/ResultDownload.tsx
  src/services/modelApi.ts
  src/services/reviewApi.ts
  src/types/model.ts
Labels: ✨ Feature, 🎨 Desgin
